primary:
  persistence:
    storageClass: hcloud-volumes
    size: 10Gi
  initdb:
    scripts:
      grant_superuser.sh: |
        #!/bin/bash
        PGPASSWORD=$(cat /opt/bitnami/postgresql/secrets/postgres-password) \
          psql -U postgres -c "ALTER USER chatwoot SUPERUSER;"

auth:
  database: chatwoot_production
  username: chatwoot
  # password set via --set auth.password=... at install time
